fullnameOverride: "aws-fluent-bit-infrastructure"

cloudWatch:
  logGroupName: "/aws/eks/eks-fluentbit/infrastructure"
  logStreamPrefix: "prod-infra-"

input:
  # Pattern specifying a specific log file or multiple ones through the use of common wildcards.
  extraInputs: |
    Exclude_Path     /var/log/containers/*_application_*.log,/var/log/containers/*_kubernetes-dashboard_*.log
